language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - echo "We can put normal shell commands here"
  - echo "new statement where added to test the CI code"
  - echo "We can put shell commands here"
  - echo "We can put shell commands here"
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master 
